### DISCUSSION TITLE
Separate local release actions from publishing

### DISCUSSION THREAD

**Discussion by laughedelic** [intuit/auto#1965] [Q&A]
First a concrete use case: I want to run Auto with the `git-tag` plugin, but I need to do things after the tag is created, but before it is pushed. Similar to the setup with `exec` plugin I mentioned [here](https://github.com/intuit/auto/discussions/1953#discussioncomment-634981), but this time my actions don't fit in a single script that I can call from `exec`. 

I see that `git-tag` plugin bumps the version and creates a tag in the [`version` hook](https://github.com/intuit/auto/blob/main/plugins/git-tag/src/index.ts#L65) and pushes it in the [`publish` hook](https://github.com/intuit/auto/blob/main/plugins/git-tag/src/index.ts#L116). But how can I trigger these hooks from the CLI? I want to do this:

- run what's in git-tag's `auto.hooks.version`
- ...do my stuff...
- run what's in git-tag's `auto.hooks.publish`

Unintuitively, `auto version` is not related to the `auto.hooks.version` in the code, so calling `auto version` tells me, e.g. `patch`, but doesn't create the tag locally. Even if I get the version by running `auto latest --dry-run --quiet` and create the tag manually (as a workaround), how do I call the `auto.hooks.publish` from the CLI?

---

More generally: is it possible to do a release preparation (all local actions) separately from the publishing/pushing those changes? Something like

```
auto shipit --no-publish
# ... do things
auto shipit --carry-on 
```

And if it's not possible at the moment, can this be implemented with the current Auto architecture? I would be glad to contribute it, if you can give me some pointers 🙂 

---

P.S. motivation for this:

> For the majority of "package manager" plugins you should only use one at a time. Using multiple will lead to undesired results.

(quoting docs) and my comment here: https://github.com/intuit/auto/issues/917#issuecomment-825274076. 

I need to publish two different kinds of artifacts from the same project (not npm, not a monorepo), versioning is simple and is based on git tags and git describe (for canaries), so I don't really need publishing plugins and would be happy with the `git-tag` plugin, if the functionality described above was supported: bump version, create tag, _do my custom publishing_, push the tag, publish GitHub release, etc.

Having this would actually eliminate the need to write plugins for those use-cases where there is no manifest file with the version value: sbt, Docker, GitHub Actions, custom artifact upload, etc.

**Comment by hipstersmoothie** [comment]
I think the flags you describe are cool but hard with the current code. 

I feel like you em use case could mostly be covered with the afterVersion hook in the exec plugin. 

Have your thoughts changed at all since writing a plugin?

**Reply by laughedelic** [reply]
> I feel like you em use case could mostly be covered with the afterVersion hook in the exec plugin.

I mentioned above:

> setup with exec plugin I mentioned here, but this time my actions don't fit in a single script that I can call from exec.

Using `exec` plugin is very restrictive: everything needs to be done in a single script. If I'm running release process on GitHub Actions, I want to be able to use actions as part of the release process, something along the lines of 

```yaml
jobs:
  release:
    steps:
      # ... setup ...

      - run: auto shipit --no-publish

      # my custom publishing actions with the newly created tag
      - run: sbt publish
      - uses: docker/build-push-action@v2
        with:
          ...
      - uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          ...
      # etc. other steps/actions

      - run: auto shipit --publish
```

Sure, everything can be done in a bash script, but that kind of destroys the point of using GitHub Actions.
