### DISCUSSION TITLE
"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them"

### DISCUSSION THREAD

**Discussion by lloydjatkinson** [intuit/auto#2293] [Q&A]
I have no idea what this means. I have checked most of the permissions when creating the GitHub Actions token.

Does Auto only work with public repos? I ran `auto init` and it created the `.env` file. It used the token in there to setup the labels to begin with, so it must be able to work with private repos, right?

What permissions does Auto need in the token exactly? Kind of a frustrating experience for a first time user of this tool.

```
RequestError [HttpError]: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}
    at /home/runner/work/date-fns-additional/date-fns-additional/node_modules/@octokit/request/dist-src/fetch-wrapper.js:68:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by hipstersmoothie** [comment]
The GitHub action experience is tough to nail. I haven't really round a config I like for all situations. Did you end up fixing this?

**Comment by aldrichdev** [comment]
I also ran into this issue. The problem appears to be with the `permissions` set in the `.yml` file, as setting `permissions: write-all` seems to fix this error. However, that isn't a good solution as it opens up more permissions than you may want to allow.

The solve for me was to use the permissions listed in this file: https://github.com/intuit/auto/blob/main/.github/workflows/build.yml, plus `packages: write` in my case, as I am trying to create an NPM package in GitHub as part of my action. For clarity, the full config looks like this:

```
    permissions:
      # To be able to push to the repo
      contents: write
      # To update the PR description with canary info
      pull-requests: write
      # For pr-check to create a status
      statuses: write
      # Needed to create PR statuses/checks
      checks: write
      # To post comments on PRs
      issues: write
      # To create NPM packages in GitHub
      packages: write
```

You can put that above your `steps` in the action, or above `jobs` (where Auto has it).
