### ISSUE TITLE
Chrome Extension manifest.json in .gitignore

### ISSUE THREAD

**Issue by lucascurti** [intuit/auto#1158]
**Describe the bug**

I'm trying to setup `auto` to publish a Chrome Extension. I've added a Github Action that builds the extension in a `./build` folder before running `npx auto shipit`. This is the folder that will be compressed in a ZIP to be published and it's added to `.gitignore` since I don't want to commit it.

The problem is that when `npm auto shipit` runs seems it's trying to add the manifest from this folder but fails because the folder is in `.gitignore`.

Any idea how to fix this and still have the `build` folder in `.gitignore`?

**Error Message**
```
Error: Running command 'git' with args [add, ./build/manifest.json] failed

The following paths are ignored by one of your .gitignore files:
build/manifest.json
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"

    at ChildProcess.<anonymous> (/home/runner/work/client-extension/client-extension/node_modules/@auto-it/core/dist/utils/exec-promise.js:49:24)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
##[error]Process completed with exit code 1.

```
**.autorc**

```json
{
  "plugins": [
    "released",
    [
      "chrome",
      {
        "id": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
        "build": "./build",
        "manifest": "./build/manifest.json"
      }
    ]
  ]
}
```

**Github Action**
```yaml
name: Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          submodules: "recursive"

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEV_SECRET }}
          REFRESH_TOKEN: ${{ secrets.DEV_REFRESH_TOKEN }}
        run: |
          npm install
          npm run build
          npx auto shipit

```
