### ISSUE TITLE
`auto version` not returning a value

### ISSUE THREAD

**Issue by RichieRunner** [intuit/auto#1367]
I have 2 released PRs that I'm expecting to be attached to the same version and github release:
- first PR: not labeled. Should default to `patch` according to doco.
- second PR: labled as `minor` and `release`

When I ran `auto version` to bump the version (to minor), `auto version` did not return any value. It was blank in both local and CI environment (AWS Codebuild). I'm suspecting it could have something to do with that first PR that was not labeled?

What should I do to combine multiple PRs to one release?

**Comment by hipstersmoothie** [comment]
`auto version` will calculate the version using all the commits since the last `Latest Release`. So if there has been multiple PRs in that time they will all be used to calculate the version.

`auto version` will return nothing if either:

1. a `skip-release` label is present
2. or you're only releasing with the `release` label and it is not present.

Try running `auto version -vv` and posting the result here

**Comment by RichieRunner** [comment]
![image](https://user-images.githubusercontent.com/20289967/87209677-9d350700-c2c7-11ea-8be9-68c0d8de1632.png)


![image](https://user-images.githubusercontent.com/20289967/87209626-6a8b0e80-c2c7-11ea-8eb3-ab95709d8ba3.png)


![image](https://user-images.githubusercontent.com/20289967/87209554-2992fa00-c2c7-11ea-8fb8-9da4783bba17.png)

**Comment by hipstersmoothie** [comment]
Is that a log from `shipit` I have a feeling this is because you aren't using the npm plugin and as a result I don't think you are properly tagging the release.

when the `release` portion of `shipit` runs it expects there to a be a new tag at the head or for the version to have incrementedf. 

So for example: if the last tag in your branch is 2.1.0 it will try to create a release for that tag. Since that version already has a release nothing happens.

Could you share your autorc? I can't really think of anything that would make that plugin not work other than a configuration error

**Comment by RichieRunner** [comment]
my `.autorc` file:
``` json
{
  "owner": "xxx",
  "repo": "xxx",
  "name": "xxx",
  "email": "xxx",
  "githubApi": "https://xxx.coxautoinc.com/api/v3",
  "githubGraphqlApi": "https://xxx.coxautoinc.com/api",
  "plugins": ["released"]
}
```

my custom CI script to do releasing:
``` bash
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - apt-get update
      - apt-get install -y jq
      - echo Build enviromment `uname -a` `aws --version 2>&1` node/`node --version` npm/`npm --version`
      - echo $(env)

  pre_build:
    commands:
      #######################################################################
      - echo **** Running Prebuild ****
      #######################################################################
      - cd ${CODEBUILD_SRC_DIR}/
      - npm ci
      - cd ${CODEBUILD_SRC_DIR}/
      - npm install -g auto
      
      - git remote set-url origin https://xxx
      - git checkout master
      - git config --global user.email "xxx"
      - git config --global user.name "xxx"
      
      - auto version
      - VERSION=`auto version`
      - echo $VERSION
      
      - npm version ${VERSION} -m "Bump version"
      
      - git push --verbose --follow-tags --set-upstream origin master
      - auto release -v

      ```

**Comment by hipstersmoothie** [comment]
As I said in the other issue you gotta do this. All the repos you link do this

```json
{
 // wrong
 "plugins": ["released"],
 // correct
 "plugins": ["npm", "released"],
}
```

**Comment by RichieRunner** [comment]
> Is that a log from `shipit` I have a feeling this is because you aren't using the npm plugin and as a result I don't think you are properly tagging the release.
> 
> when the `release` portion of `shipit` runs it expects there to a be a new tag at the head or for the version to have incrementedf.
> 
> So for example: if the last tag in your branch is 2.1.0 it will try to create a release for that tag. Since that version already has a release nothing happens.
> 
> Could you share your autorc? I can't really think of anything that would make that plugin not work other than a configuration error

I am not explicitly running `git tag` or anything similar anywhere. I assume this is the responsibility of `auto`

**Comment by hipstersmoothie** [comment]
Only the `shipit` command will do that. since you switched to the manual setup you would need to run `npm publish` as well.

But I think if you switch to shipit with the correct plugin config it will work.

1. fix including npm plugin in autorc
2. replace all auto script lines with `auto shipit`

**Comment by RichieRunner** [comment]
> Only the `shipit` command will do that. since you switched to the manual setup you would need to run `npm publish` as well.
> 
> But I think if you switch to shipit with the correct plugin config it will work.
> 
> 1. fix including npm plugin in autorc
> 2. replace all auto script lines with `auto shipit`

Thanks, that solved my new problem! But now we're back to my original question, is how do I combine multiple PRs into one release:
)
![image](https://user-images.githubusercontent.com/20289967/87211498-8cd45a80-c2ce-11ea-90f2-37afe187b37b.png)

![image](https://user-images.githubusercontent.com/20289967/87211469-74fcd680-c2ce-11ea-88d8-013de0082d78.png)

**Comment by hipstersmoothie** [comment]
40 def should have been included. that might be a bug. but I do this all the time and it should've worked

**Comment by hipstersmoothie** [comment]
I'm testing on one of my test repos. just did the same thing you did https://circleci.com/gh/hipstersmoothie/auto-single-package/173?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hipstersmoothie** [comment]
https://github.com/hipstersmoothie/auto-single-package/releases/tag/v0.0.23-next.0

**Comment by RichieRunner** [comment]
I tried a few more things:
  - removed the following: still didn't work
    - ```
      - git remote set-url origin https://xxx
      - git checkout master
      - git config --global user.email "xxx"
      - git config --global user.name "xxx"
      ```
  - removed "released" plugin: still didn't work

I noticed that you also run individual Release pipeline for your feature branches once they get merged it. `auto shipit` is also raun on those branches? I only run `auto shipit` on my main `master` branch. Does that make a difference?
![image](https://user-images.githubusercontent.com/20289967/87217542-36cbdb00-c2ff-11ea-8f59-d655e41896af.png)

**Comment by hipstersmoothie** [comment]
That will release a “canary” version of the code people can install to test the pr. This shouldn’t effect the latest release when ran from master.

**Comment by hipstersmoothie** [comment]
You can see that here https://github.com/hipstersmoothie/auto-single-package/pull/28

**Comment by hipstersmoothie** [comment]
You might be running into this issue https://intuit.github.io/auto/docs/welcome/quick-merge. But the window for it to happen should be very short, the timing would have to be almost perfect.

I feel like I haven't really answered you question.

**Q:** What are the ways to release multiple commits in a release?

1. use the `skip-release` label on a PR. that PR should still be included in the next release. but when merged will not generate a release
2. [use this config option](https://intuit.github.io/auto/docs/configuration/autorc#only-publish-with-release-label) and only generate a release when a `release` label is attached. you still add semver patches as you go. 

Since this is on a GitHub instance I can't see it's gonna be hard to debug further. I would be open to doing a zoom call to see what's up if the problem persists

**Comment by RichieRunner** [comment]
@hipstersmoothie I've replicated the issue on a public repo here: https://github.com/RichieRunner/node-test/releases
I don't use CircleCI, so you'll have to create a CircleCI build to test. (I'm beginning to suspect that the crux of all my issues is really from using AWS Codebuild and not CircleCI like most repos that are using `auto`).

**Comment by hipstersmoothie** [comment]
I've never personally build on codebuild. `auto` is also on travis, jenkins, and github actions too. 

I'll take a look at this today!

**Comment by hipstersmoothie** [comment]
Pulling the project locally I was able to create the right changelog.

1. HEAD set at latest master
2. `yarn auto changelog --from v1.0.1 -d`

```
 #### 🚀 Enhancement

- Update README.md [#5](https://github.com/RichieRunner/node-test/pull/5) ([@RichieRunner](https://github.com/RichieRunner))

#### 🐛 Bug Fix

- Update index.js [#6](https://github.com/RichieRunner/node-test/pull/6) ([@RichieRunner](https://github.com/RichieRunner))

#### ⚠️ Pushed to `master`

- Update package.json ([@RichieRunner](https://github.com/RichieRunner))

#### Authors: 1

- Richie ([@RichieRunner](https://github.com/RichieRunner))
```

So i'm leaning towards this being an AWS codebuild issue. I've never used that platform before. Any chance you could get this project running on that and give me access? And if not just provide me the ***full*** output log when ran with -vv. Without the full log I can't really debug this

**Comment by loreina** [comment]
Is there an update on this? publishing to GPR using a Github Action workflow doesn't seem to work for me, and I think it might be due to `auto version` not returning a value, so version isn't bumped in `package.json` or `package-lock.json`.

this is my `release.yml`:

```
name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Create release
        run: npx auto shipit -m "release [skip ci]"
        env:
          GH_TOKEN: ${{ secrets.REPO_SCOPE_TOKEN }}

      - name: Bump version
        run: npm version `auto version`
        env:
          GH_TOKEN: ${{ secrets.REPO_SCOPE_TOKEN }}
```

**Comment by jscheel** [comment]
I've run into this as well. All of the sudden, I can't get a release to go out. The changelog is generated properly, the PR has the `release` and `patch` labels on it, but it doesn't actually bump the version so it won't make a release.

**Comment by hipstersmoothie** [comment]
@jscheel Could link me to the CI job or post a log with `-vv` turned on?

**Comment by jscheel** [comment]
I am running it on metal, not in a CI job. I’m out of town for the weekend,
but I can can post on Monday. It actually worked fine when I used shipit,
which I’ve never used before.

**Comment by travis-crowder-kr** [comment]
I have this issue as well ... `auto version` returning no value.

NodeJS Version: v14.17.3
Ubuntu 20.04.2 LTS

Environment: ubuntu-20.04
  Version: 20210726.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210726.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210726.1

# .autorc
```
{
  "plugins": [
    "git-tag"
  ],
  "owner": "qwerty",
  "repo": "hw-qwerty",
  "name": "GitHub Bot",
  "email": "no-reply@qwerty.com",
  "onlyPublishWithReleaseLabel": true
}
```
# Tool install step
```
- name: Install tools
  run: |
    mkdir -p ~/.local/bin && npm config set prefix '~/.local/' && \
    npm install -g doctoc auto @auto-it/git-tag
```

# Run tool step
```
- name: Run tools
  run: |
    ~/.local/bin/auto version
```

# Result
No return value

# Changed to auto shipit -dq
```
- name: Run tools
  run: |
    ~/.local/bin/auto shipit -dq
```

# Changed to auto -vv shipit -dq
```
- name: Run tools
  run: |
    ~/.local/bin/auto -vv shipit -dq
```

# Result
No return value

# Getting the exit code
```
~/.local/bin/auto -vv shipit -dq
  echo "Retval: $?"
```

# Result
0

# PR Information
patch and release label applied

# Interesting final note
Running our final shipit works just fine and does everything expected.

```
- name: Create a GitHub release
        # only run against main and NOT a PR (i.e. a merge to main == build release)
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           ~/.local/bin/auto shipit
```

# Reason for desired bug to be resolve
Looking to get the anticipated version number so I can sed replace versions in example/demo files.
