### ISSUE TITLE
auto shipit not bumping version

### ISSUE THREAD

**Issue by puzzledbytheweb** [intuit/auto#1400]
**Describe the bug**

In my CircleCI config I'm calling `npx auto shipit`, as specified in the docs. 

**To Reproduce**

 - Make a change
 - Open a PR
 - Add the "major" and the "release" labels
 - Merge and let CircleCI do its magic

**Expected behavior**
I expect this to bump my version and make a new release in Github.

**Environment information:**

In the beginning of the script output it says this:
`✔  success   Calculated version bump: major`

Then this:
`ℹ  info      Current "Latest Release" on Github: v1.1.0`

If I run `auto shipit --verbose | grep "Calculated next version"` it outputs:
 `ℹ  info      Calculated next version to be: 2.0.0`

Running `auto shipit -vv`:
`ℹ  info      No previous release found, using 0.0.0 as previous version.`
`ℹ  info      Using latest release as previous version`

And finally, instead of bumping to "v2.0.0" it's outputting this:
`⚠  warning   Nothing released to Github. Version to be released is the same as the latest release on Github: v1.1.0` 

**Additional context**

`npm auto info`:
```
Environment Information:

"auto" version: v9.48.1
"git"  version: v2.24.3
"node" version: v14.5.0

Project Information:

✔ Repository:     private-repo
✔ Author Name:     puzzledbytheweb
✔ Author Email:    pmsfilipe1@gmail.com
✔ Current Version: v1.1.0
✔ Latest Release:  v1.1.0 (​private-repo/releases/tag/v1.1.0​)

✔ Labels configured on GitHub project 

GitHub Token Information:

✔ Token:            [Token starting with de85]
✔ Repo Permission:  write
✔ User:             org bot
✔ API:              undefined (​undefined​)
✔ Enabled Scopes:   admin:org, notifications, read:packages, repo, user, write:discussion, write:packages
✔ Rate Limit:       4923/5000
```

**Comment by hipstersmoothie** [comment]
Could you post your .autorc too? If this is a private repo a full log would help too

**Comment by puzzledbytheweb** [comment]
```
{
  "plugins": [
  ],
  "owner": "ovotech",
  "repo": "hello_world",
  "name": "puzzledbytheweb",
  "email": "pmsfilipe1@gmail.com",
  "onlyPublishWithReleaseLabel": false
}
```

Previously `onlyPublishWithReleaseLabel` was set to `true`.

**Comment by hipstersmoothie** [comment]
What type of project are you trying to release?

**Comment by puzzledbytheweb** [comment]
A normal app. It exposes some endpoints, nothing fancy really

**Comment by hipstersmoothie** [comment]
but like to npm, a git tag, a cocoapod. etc?

**Comment by puzzledbytheweb** [comment]
We're trying to do a simple git tag

**Comment by hipstersmoothie** [comment]
Sweet! all you need to do is add the `git-tag` plugin to your `.autorc`. If you're using npm you will have to install `@auto-it/git-tag`, and if you're using the binary it's already installed.

```json
{
  "plugins": [
    'git-tag'
  ],
  "owner": "ovotech",
  "repo": "hello_world",
  "name": "puzzledbytheweb",
  "email": "pmsfilipe1@gmail.com",
  "onlyPublishWithReleaseLabel": false
}
```

https://intuit.github.io/auto/docs/configuration/plugins

**Comment by puzzledbytheweb** [comment]
I installed `@auto-it/git-tag`, adding it to the `.autorc` and it now works when I run it manually!

It doesn't work in CircleCI though :/ it says:
`⚠  warning   Could not find plugin: git-tag`

 I remember when I first installed `auto` that there was some issue with the plugin git-tag not being found, through `auto init`. Do you have any idea on that?

**Comment by hipstersmoothie** [comment]
are you sure you added it to you deps in your package.json? are all your deps on the same version of auto (this shouldn't matter for this case though)

**Comment by puzzledbytheweb** [comment]
I'm pretty sure but perhaps there is some issue with caching? I'll only be able to check that either this weekend or on Monday.

**Comment by hipstersmoothie** [comment]
This is a pretty odd issue. If you could sanitized the output of a run with `-vv` I may be able to debug without seeing the repo.

**Comment by puzzledbytheweb** [comment]
Sure! Tomorrow I'll do it. I need to do it from my work computer.

Andrew Lisowski <notifications@github.com> escreveu no dia sexta,
24/07/2020 à(s) 20:47:

**Comment by puzzledbytheweb** [comment]
Here it is. Thank you for your help so far. I hope we're almost there!

[auto.log](https://github.com/intuit/auto/files/4975620/auto.log)

**Comment by puzzledbytheweb** [comment]
So. I think I found out the problem as to why my CircleCI was failing. I was calling the `checkout` step before making the release, which effectively copied a fresh repo (removing the installed dependencies, which I am now persisting with `persist_to_workspace`).

Now the problem is with `package-lock.json`, which gets changed during the install job. Any idea on how to fix that?

**Comment by puzzledbytheweb** [comment]
Regarding my last comment. I ran `npm install` locally, which updated `package-lock.json`, pushed it and opened a PR. It looks like it's solved! 

I'll be closing this now.

Thanks so much for your help @hipstersmoothie !

**Comment by puzzledbytheweb** [comment]
Actually, even though the release is now made to Github and everything looks great, I'm expecting my `package.json` version to be bumped as well. 

I'm wondering if I need to enable the npm plugin, and if so, if I'm able to use it without actually publishing it to the npm registry.

Thanks in advance!

**Comment by hipstersmoothie** [comment]
Sorry! took the weekend completely off but am back now. looking into this

**Comment by hipstersmoothie** [comment]
>  I was calling the checkout step before making the release, which effectively copied a fresh repo

Yup! in circle ci you def have to do this. If you also have a build step you must persist that work as well. Otherwise your `dist` files won't be in the release

> Regarding my last comment. I ran npm install locally, which updated package-lock.json, pushed it and opened a PR. It looks like it's solved!

You are correct. This is the same with yarn. Your lockfile must be up to date before releasing

> When I run auto shipit locally it changes CHANGELOG.md, but then I have to commit it manually and push it to master. This doesn't work in CircleCI because the environment is ephemeral. The file is changed but, since it goes away after the job, it's useless.

When auto pushes the tag it creates it should also push this commit as well as any version changes.

> I'm wondering if I need to enable the npm plugin, and if so, if I'm able to use it without actually publishing it to the npm registry.

if you're trying to use the npm plugin with a private package [I just made that work](https://github.com/intuit/auto/pull/1397)

**Comment by puzzledbytheweb** [comment]
> When auto pushes the tag it creates it should also push this commit as well as any version changes.

Unfortunately it looks like it's not doing so. I do get the tag pushed and released but any change it does to the `CHANGELOG.md` dies there. That doesn't happen when running `auto shipit` locally.

Am I missing something or is this a bug? Here's my sanitized CircleCI config:
```yaml
aliases:
  - &restore-cache
    keys:
      # Find a cache corresponding to this specific package.json checksum
      # when this file is changed, this key will fail
      - dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      - dependency-cache-{{ checksum "package-lock.json" }}
      # Find the most recent cache used from any branch
      - dependency-cache-
  - &save-cache
    key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - node_modules
  - &only-master
    branches:
      only:
        - master

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Release
          command: npx auto shipit -v

workflows:
  version: 2
  build:
    jobs:
      - install
      - release:
          requires:
            - install
          filters:
            <<: *only-master
```

> if you're trying to use the npm plugin with a private package I just made that work

Not for this project but definitely will take a look once that's needed 👍
