### ISSUE TITLE
No changelog/version bump commits or release tagged (Github Actions)

### ISSUE THREAD

**Issue by benskz** [intuit/auto#1687]
**Describe the bug**

I'm trying to setup auto without running `auto shipit` as I don't want to publish anything. However, it does not appear that the version bumps are being committed and the release command does not detect a new version either. I'm assuming my setup is missing a step between the versioning and the release commands.

Thanks for your help.

**To Reproduce**

Scripts:
```
"autoversion": "npm version `auto version` -m 'ci: bump version to: %s [skip ci]'",
"release": "auto changelog && yarpm-yarn autoversion && auto release"
```

What I'm running in CI (Github Actions) after `yarn install`:
```
- name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
```

**Expected behavior**

`auto changelog` should commit the changelog changes, `yarn autoversion` (see script above) should commit new version bump and `auto release` should generate a new github release.

**Additional context**

Here is the CI output where you can see that `auto version` is correctly outputting the new version number.
```
Run yarn release
yarn run v1.22.5
$ auto changelog && yarpm-yarn autoversion && auto release
{ Change log updates are shown correctly here }
$ npm version `auto version` -m 'ci: bump version to: %s [skip ci]'
v1.1.0
{ Change log updates are shown correctly here }
⚠  warning   Nothing released to Github. Version to be released is the same as the latest release on Github: v1.0.0
Done in 10.91s.
```
