### ISSUE TITLE
auto version returns no value and exit code 0

### ISSUE THREAD

**Issue by travis-crowder-kr** [intuit/auto#2041]
I have this issue as well ... `auto version` returning no value.

NodeJS Version: v14.17.3
Ubuntu 20.04.2 LTS

Environment: ubuntu-20.04
  Version: 20210726.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210726.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210726.1

# .autorc
```
{
  "plugins": [
    "git-tag"
  ],
  "owner": "qwerty",
  "repo": "hw-qwerty",
  "name": "GitHub Bot",
  "email": "no-reply@qwerty.com",
  "onlyPublishWithReleaseLabel": true
}
```
# Tool install step
```
- name: Install tools
  run: |
    mkdir -p ~/.local/bin && npm config set prefix '~/.local/' && \
    npm install -g doctoc auto @auto-it/git-tag
```

# Run tool step
```
- name: Run tools
  run: |
    ~/.local/bin/auto version
```

# Result
No return value

# Changed to auto shipit -dq
```
- name: Run tools
  run: |
    ~/.local/bin/auto shipit -dq
```

# Changed to auto -vv shipit -dq
```
- name: Run tools
  run: |
    ~/.local/bin/auto -vv shipit -dq
```

# Result
No return value

# Getting the exit code
```
~/.local/bin/auto -vv shipit -dq
  echo "Retval: $?"
```

# Result
0

# PR Information
patch and release label applied

# Interesting final note
Running our final shipit works just fine and does everything expected.

```
- name: Create a GitHub release
        # only run against main and NOT a PR (i.e. a merge to main == build release)
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           ~/.local/bin/auto shipit
```

# Reason for desired bug to be resolve
Looking to get the anticipated version number so I can sed replace versions in example/demo files.
