### ISSUE TITLE
github action locked during make change note

### ISSUE THREAD

**Issue by walt1992** [intuit/auto#2269]
**Describe the bug**

I made workflow to release using auto.
but, release process is stopped (not error). this is workflow log 

```
1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "auto > @auto-it/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "auto > @auto-it/core > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
warning "auto > @auto-it/core > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...
Done in 5.11s.
✔  success   Calculated version bump: minor
ℹ  info      New Release Notes
 #### 🚀 Enhancement

- feat: test [#7](https://github.com/bucketplace/fe-package-release-poc/pull/7) ([@walt[19](https://github.com/bucketplace/fe-package-release-poc/actions/runs/3342230588/jobs/5534245500#step:5:20)92](https://github.com/walt1992))
- feat: test [#6](https://github.com/bucketplace/fe-package-release-poc/pull/6) ([@walt1992](https://github.com/walt1992))
- Test/test1 [#3](https://github.com/bucketplace/fe-package-release-poc/pull/3) ([@walt1992](https://github.com/walt1992))

#### 🐛 Bug Fix

- feat: test [#9](https://github.com/bucketplace/fe-package-release-poc/pull/9) ([@walt1992](https://github.com/walt1992))
- feat: test [#8](https://github.com/bucketplace/fe-package-release-poc/pull/8) ([@walt1992](https://github.com/walt1992))
- feat: test [#5](https://github.com/bucketplace/fe-package-release-poc/pull/5) ([@walt1992](https://github.com/walt1992))
- feat: test [#4](https://github.com/bucketplace/fe-package-release-poc/pull/4) ([@walt1992](https://github.com/walt1992))
- Test/test1 [#2](https://github.com/bucketplace/fe-package-release-poc/pull/2) ([@walt1992](https://github.com/walt1992))
- feat: test [#1](https://github.com/bucketplace/fe-package-release-poc/pull/1) ([@walt1992](https://github.com/walt1992))

#### ⚠️ Pushed to `main`

- chore: 초기세팅 ([@walt1992](https://github.com/walt1992))

#### Authors: 2

- Walt Park ([@walt1992](https://github.com/walt1992))
Error: The operation was canceled.
```

This doesn't keep going, So I cancel it by myself.
What cause this?

**To Reproduce**

this is my workflow

```
name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Prepare repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install yarn
        run: npm i --location=global yarn

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd packages/auto-poc
          yarn install --frozen-lockfile
          npx auto latest --no-changelog

```

**Expected behavior**

smoth release

**Screenshots**

<img width="2128" alt="image" src="https://user-images.githubusercontent.com/37332261/198454359-41cb6f9c-5c8e-4f37-8d17-0c29dc64b464.png">
**Environment information:**

github action worklfow
