### ISSUE TITLE
Generates a 404 error in npm when attempting to access a repository within a GitHub organization

### ISSUE THREAD

**Issue by cmarin001** [intuit/auto#2447]
**Describe the bug**

I've attempted this configuration because it performed quite well on a personal repository of mine. However, when applied to a repository within a GitHub organization of which I am a member, it fails to work at all.

```
name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  autorelease:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          scope: "@mockscope"
          always-auth: true

      - name: Configure Git
        run: |
          git config --global user.email user@example.com
          git config --global user.name YourUsername

      - name: Configure npm
        run: |
          echo "@mockscope:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Install Dependencies
        run: npm install

      - name: Run auto shipit
        run: npx auto shipit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
And whenever I try this, this issue occurs.

![image](https://github.com/intuit/auto/assets/45011420/f064778b-11cc-480b-83cb-d3bacbf8bbfc)

I generated the automation token on npm and also tried creating a GH_TOKEN with full permissions, but unfortunately, neither approach was successful
