### ISSUE TITLE
`No previous release found` on a project which has previous releases and tags

### ISSUE THREAD

**Issue by andersfischernielsen** [intuit/auto#2486]
I'm trying to set up Auto as our release tool. I've written a GitHub workflow which does the following: 

```yaml
name: Release

on:
  push:
    branches:
      - main

jobs:
  changelog:
    name: Release
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}"
    needs:
      - deploy-device-api
      - deploy-brisk-platform
    permissions:
      issues: read
      pull-requests: read
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        run: git fetch --unshallow --tags

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Generate release
        run: bunx auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Looking at the `-vv` output for `shipit` or `release` I see the following: 

```
ℹ  info      No previous release found, using 0.0.0 as previous version.
ℹ  info      Using latest release as previous version
```

The project has several releases on GitHub: `v0.0.0` and `v.0.0.1`. I also tried tagging and naming these releases `0.0.0` and `0.0.1` just to understand the behavior of Auto.
 
I've tried setting the version in `package.json` to both `0.0.0` and `v0.0.0`. 

I've added the `minor` label to a previous PR merged on the branch and `auto version` shows `minor` as expected. The `CHANGELOG` is also generated and shown as expected, but then Auto exits with: 

```
⚠  warning   Nothing released to Github. Version to be released is the same as the latest release on Github: v0.0.1
```

I've tried running the app locally with a token with the same permissions as the GitHub workflow _and_ with a GitHub PAT which has _all_ permissions set to read and write, with no luck.

My `package.json` has the following `"auto"` section: 

```json
{
  "auto": {
    "plugins": [],
    "author": "Auto <software@reshapebiotech.com>"
  }
}
```

No matter what I try, Auto refuses to detect the previous releases and/or release a new release.

**To Reproduce**

- Run `auto shipit -vv` or `auto release -vv`

**Expected behavior**

Auto releases a minor version bump.

**Screenshots**

<img width="832" alt="Image" src="https://github.com/user-attachments/assets/f276a457-802a-4c17-ac73-1d5ea3e42f19" />

**Environment information:**

```txt
Environment Information:

"auto" version: v11.3.0
"git"  version: v2.39.5 (Apple Git-154)
"node" version: v23.5.0

Project Information:

✔ Repository:      reshapebiotech/brisk
✔ Author Name:     Anders Fischer-Nielsen
✔ Author Email:    nope@nothanks.com
✔ Current Version: v0.0.1
✔ Latest Release:  v0.0.1

✖ Labels configured on GitHub project (Try running "auto create-labels")

GitHub Token Information:

✔ Token:            [Token starting with ghp_]
✔ Repo Permission:  admin
✔ User:             andersfischernielsen
✔ API:
✔ Enabled Scopes:   admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, admin:ssh_signing_key, audit_log, codespace, copilot, delete:packages, delete_repo, gist, notifications, project, repo, user, workflow, write:discussion, write:packages
✔ Rate Limit:       4778/5000
```
