### ISSUE TITLE
How to use shipit to create a github release but not deploy to npm?

### ISSUE THREAD

**Issue by Tasemu** [intuit/auto#2497]
Hi there, i have a workflow which I want to use for handle my versioning and changelog for my personal project. I workflow fails every time as it appears to be trying to deploy to NPM, this isn't a package so i was hoping there was a way to achieve this just on the google releases side and not the npm. So i can make a PR with the patch label, it will generate the changelog and the new version when i merge it into main?

```
name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags  # Only needed if you require full git history/tags

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          # Remove cache setting if you don't need npm/yarn caching

      - name: git-setup
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Only needed for GitHub releases
        run: npx auto shipit
```
