### ISSUE TITLE
Having trouble using conventional commits plugin inside GitHub action

### ISSUE THREAD

**Issue by sarah-vanderlaan** [intuit/auto#775]
Is it possible to use the conventional commits plugin inside of a GitHub action?  I am having trouble configuring it.  Could you provide an example of how to use plugins inside of an action?  Thank you in advance 😃 

I have in package json:

```
  "devDependencies": {
    "@auto-it/conventional-commits": "^7.17.0",
    "auto": "^7.17.0"
  }
```

and my `.autorc` is:

```
{
    "plugins": ["conventional-commits"]
}
```

**Comment by hipstersmoothie** [comment]
@sarah-vanderlaan could you point me towards your repo? The plugin shouldn't require any setup

**Comment by sarah-vanderlaan** [comment]
@hipstersmoothie it is a private repository :( but here is package.json:

```
{
  "name": "autorelease-playground",
  "devDependencies": {
    "@auto-it/conventional-commits": "^7.17.0",
    "auto": "^7.17.0"
  },
  "version": "5.0.2",
  "description": "testing auto release",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "<PRIVATE>/autorelease-playground.git"
  },
  "author": "Sarah van der Laan <PRIVATE>",
  "license": "MIT"
}
```

and here is github action:

```
name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1
      - name: Prepare repository
        env:	
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout ${GITHUB_REF:11} --
          git remote rm origin
          git remote add origin https://$GH_TOKEN@github.com/<PRIVATE>/autorelease-playground
          git fetch origin --tags
          git branch --set-upstream-to origin/${GITHUB_REF:11} ${GITHUB_REF:11}
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn
          npx auto shipit
```

Is there anything else I can provide to help?
